version: '3'

services:
    app:
        image: node:latest
        command: npm run dev
        ports:
            - '3001:3001'
        user: node
        volumes:
            - ./app:/app
        working_dir: /app
