version: '3'

services:
    app:
        image: node:latest
        command: npm run dev -- --host
        ports:
            - '4321:4321'
        user: node
        volumes:
            - ./app:/app
        working_dir: /app
